	AREA RESET,DATA,READONLY
	EXPORT __Vectors
__Vectors
	DCD 0x40001000
	DCD Reset_Handler
	ALIGN
	AREA mycode,CODE,READONLY
ENTRY
	EXPORT Reset_Handler
Reset_Handler

	LDR R3,=DST
	LDR R0,=SRC
	LDR R2,[R0,#4]
	STR R1,[R3]
	STR R2,[R3,#4]
SRC DCD 0X12345678,0XABCD,0XAAAA
	AREA mydate,DATA,READWRITE
DST DCD 0X0
	END
	